// Mocks generated by Mockito 5.4.6 from annotations
// in vlvt/test/widgets/discovery_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i11;

import 'package:flutter/material.dart' as _i17;
import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:purchases_flutter/purchases_flutter.dart' as _i16;
import 'package:purchases_ui_flutter/purchases_ui_flutter.dart' as _i15;
import 'package:vlvt/models/match.dart' as _i13;
import 'package:vlvt/models/message.dart' as _i6;
import 'package:vlvt/models/profile.dart' as _i3;
import 'package:vlvt/services/auth_service.dart' as _i2;
import 'package:vlvt/services/base_api_service.dart' as _i4;
import 'package:vlvt/services/chat_api_service.dart' as _i12;
import 'package:vlvt/services/discovery_preferences_service.dart' as _i7;
import 'package:vlvt/services/location_service.dart' as _i18;
import 'package:vlvt/services/profile_api_service.dart' as _i8;
import 'package:vlvt/services/subscription_service.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthService_0 extends _i1.SmartFake implements _i2.AuthService {
  _FakeAuthService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfile_1 extends _i1.SmartFake implements _i3.Profile {
  _FakeProfile_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResult_2<T1> extends _i1.SmartFake implements _i4.ApiResult<T1> {
  _FakeApiResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_3 extends _i1.SmartFake implements _i5.Response {
  _FakeResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMessage_4 extends _i1.SmartFake implements _i6.Message {
  _FakeMessage_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDiscoveryFilters_5 extends _i1.SmartFake
    implements _i7.DiscoveryFilters {
  _FakeDiscoveryFilters_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileApiService extends _i1.Mock implements _i8.ProfileApiService {
  MockProfileApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i2.AuthService get authService => (super.noSuchMethod(
        Invocation.getter(#authService),
        returnValue: _FakeAuthService_0(
          this,
          Invocation.getter(#authService),
        ),
      ) as _i2.AuthService);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<_i3.Profile> getProfile(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [userId],
        ),
        returnValue: _i10.Future<_i3.Profile>.value(_FakeProfile_1(
          this,
          Invocation.method(
            #getProfile,
            [userId],
          ),
        )),
      ) as _i10.Future<_i3.Profile>);

  @override
  _i10.Future<List<_i3.Profile>> getDiscoveryProfiles({
    int? minAge,
    int? maxAge,
    double? maxDistance,
    List<String>? interests,
    List<String>? excludeUserIds,
    bool? verifiedOnly,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDiscoveryProfiles,
          [],
          {
            #minAge: minAge,
            #maxAge: maxAge,
            #maxDistance: maxDistance,
            #interests: interests,
            #excludeUserIds: excludeUserIds,
            #verifiedOnly: verifiedOnly,
          },
        ),
        returnValue: _i10.Future<List<_i3.Profile>>.value(<_i3.Profile>[]),
      ) as _i10.Future<List<_i3.Profile>>);

  @override
  _i10.Future<_i3.Profile> createProfile(_i3.Profile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProfile,
          [profile],
        ),
        returnValue: _i10.Future<_i3.Profile>.value(_FakeProfile_1(
          this,
          Invocation.method(
            #createProfile,
            [profile],
          ),
        )),
      ) as _i10.Future<_i3.Profile>);

  @override
  _i10.Future<_i3.Profile> updateProfile(_i3.Profile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [profile],
        ),
        returnValue: _i10.Future<_i3.Profile>.value(_FakeProfile_1(
          this,
          Invocation.method(
            #updateProfile,
            [profile],
          ),
        )),
      ) as _i10.Future<_i3.Profile>);

  @override
  _i10.Future<Map<String, _i3.Profile>> batchGetProfiles(
          List<String>? userIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchGetProfiles,
          [userIds],
        ),
        returnValue: _i10.Future<Map<String, _i3.Profile>>.value(
            <String, _i3.Profile>{}),
      ) as _i10.Future<Map<String, _i3.Profile>>);

  @override
  _i10.Future<int> searchUserCount(Map<String, dynamic>? criteria) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchUserCount,
          [criteria],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<bool> updateLocation(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocation,
          [
            latitude,
            longitude,
          ],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<Map<String, dynamic>> uploadPhoto(String? imagePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPhoto,
          [imagePath],
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<void> deletePhoto(String? photoId) => (super.noSuchMethod(
        Invocation.method(
          #deletePhoto,
          [photoId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> reorderPhotos(List<String>? photoUrls) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderPhotos,
          [photoUrls],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<Map<String, dynamic>> swipe({
    required String? targetUserId,
    required String? action,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #swipe,
          [],
          {
            #targetUserId: targetUserId,
            #action: action,
          },
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getReceivedLikes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getReceivedLikes,
          [],
        ),
        returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getSentLikes() => (super.noSuchMethod(
        Invocation.method(
          #getSentLikes,
          [],
        ),
        returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<Map<String, dynamic>> checkProfileCompletion() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkProfileCompletion,
          [],
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<_i4.ApiResult<T>> get<T>(
    String? path, {
    T Function(Map<String, dynamic>)? parser,
    Map<String, String>? queryParameters,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #parser: parser,
            #queryParameters: queryParameters,
            #timeout: timeout,
          },
        ),
        returnValue: _i10.Future<_i4.ApiResult<T>>.value(_FakeApiResult_2<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #parser: parser,
              #queryParameters: queryParameters,
              #timeout: timeout,
            },
          ),
        )),
      ) as _i10.Future<_i4.ApiResult<T>>);

  @override
  _i10.Future<_i4.ApiResult<T>> post<T>(
    String? path, {
    Object? body,
    T Function(Map<String, dynamic>)? parser,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #body: body,
            #parser: parser,
            #timeout: timeout,
          },
        ),
        returnValue: _i10.Future<_i4.ApiResult<T>>.value(_FakeApiResult_2<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #body: body,
              #parser: parser,
              #timeout: timeout,
            },
          ),
        )),
      ) as _i10.Future<_i4.ApiResult<T>>);

  @override
  _i10.Future<_i4.ApiResult<T>> put<T>(
    String? path, {
    Object? body,
    T Function(Map<String, dynamic>)? parser,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #body: body,
            #parser: parser,
            #timeout: timeout,
          },
        ),
        returnValue: _i10.Future<_i4.ApiResult<T>>.value(_FakeApiResult_2<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #body: body,
              #parser: parser,
              #timeout: timeout,
            },
          ),
        )),
      ) as _i10.Future<_i4.ApiResult<T>>);

  @override
  _i10.Future<_i4.ApiResult<T>> delete<T>(
    String? path, {
    T Function(Map<String, dynamic>)? parser,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #parser: parser,
            #timeout: timeout,
          },
        ),
        returnValue: _i10.Future<_i4.ApiResult<T>>.value(_FakeApiResult_2<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #parser: parser,
              #timeout: timeout,
            },
          ),
        )),
      ) as _i10.Future<_i4.ApiResult<T>>);

  @override
  _i10.Future<_i5.Response> authenticatedGet(Uri? uri) => (super.noSuchMethod(
        Invocation.method(
          #authenticatedGet,
          [uri],
        ),
        returnValue: _i10.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #authenticatedGet,
            [uri],
          ),
        )),
      ) as _i10.Future<_i5.Response>);

  @override
  _i10.Future<_i5.Response> authenticatedPost(
    Uri? uri, {
    Object? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticatedPost,
          [uri],
          {#body: body},
        ),
        returnValue: _i10.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #authenticatedPost,
            [uri],
            {#body: body},
          ),
        )),
      ) as _i10.Future<_i5.Response>);

  @override
  _i10.Future<_i5.Response> authenticatedPut(
    Uri? uri, {
    Object? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticatedPut,
          [uri],
          {#body: body},
        ),
        returnValue: _i10.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #authenticatedPut,
            [uri],
            {#body: body},
          ),
        )),
      ) as _i10.Future<_i5.Response>);

  @override
  _i10.Future<_i5.Response> authenticatedDelete(Uri? uri) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticatedDelete,
          [uri],
        ),
        returnValue: _i10.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #authenticatedDelete,
            [uri],
          ),
        )),
      ) as _i10.Future<_i5.Response>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<bool> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> signInWithApple() => (super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<Map<String, dynamic>> registerWithEmail(
    String? email,
    String? password, {
    String? inviteCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerWithEmail,
          [
            email,
            password,
          ],
          {#inviteCode: inviteCode},
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmail,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<bool> forgotPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [email],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<Map<String, dynamic>> resetPassword(
    String? token,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [
            token,
            newPassword,
          ],
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<bool> resendVerificationEmail(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendVerificationEmail,
          [email],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> verifyEmail(String? token) => (super.noSuchMethod(
        Invocation.method(
          #verifyEmail,
          [token],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> setAuthData({
    required String? token,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAuthData,
          [],
          {
            #token: token,
            #userId: userId,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  _i10.Future<Map<String, dynamic>?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i10.Future<Map<String, dynamic>?>.value(),
      ) as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<Map<String, dynamic>> startIdVerification() =>
      (super.noSuchMethod(
        Invocation.method(
          #startIdVerification,
          [],
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> getIdVerificationStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getIdVerificationStatus,
          [],
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> refreshIdVerificationStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshIdVerificationStatus,
          [],
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  String getKycaidVerificationUrl(String? verificationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKycaidVerificationUrl,
          [verificationId],
        ),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #getKycaidVerificationUrl,
            [verificationId],
          ),
        ),
      ) as String);

  @override
  _i10.Future<List<_i2.ConsentStatus>> getConsents() => (super.noSuchMethod(
        Invocation.method(
          #getConsents,
          [],
        ),
        returnValue:
            _i10.Future<List<_i2.ConsentStatus>>.value(<_i2.ConsentStatus>[]),
      ) as _i10.Future<List<_i2.ConsentStatus>>);

  @override
  _i10.Future<bool> grantConsent(String? purpose) => (super.noSuchMethod(
        Invocation.method(
          #grantConsent,
          [purpose],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> withdrawConsent(String? purpose) => (super.noSuchMethod(
        Invocation.method(
          #withdrawConsent,
          [purpose],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<String?> requestDataExport() => (super.noSuchMethod(
        Invocation.method(
          #requestDataExport,
          [],
        ),
        returnValue: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ChatApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatApiService extends _i1.Mock implements _i12.ChatApiService {
  MockChatApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i2.AuthService get authService => (super.noSuchMethod(
        Invocation.getter(#authService),
        returnValue: _FakeAuthService_0(
          this,
          Invocation.getter(#authService),
        ),
      ) as _i2.AuthService);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<List<_i13.Match>> getMatches(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMatches,
          [userId],
        ),
        returnValue: _i10.Future<List<_i13.Match>>.value(<_i13.Match>[]),
      ) as _i10.Future<List<_i13.Match>>);

  @override
  _i10.Future<List<_i6.Message>> getMessages(String? matchId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [matchId],
        ),
        returnValue: _i10.Future<List<_i6.Message>>.value(<_i6.Message>[]),
      ) as _i10.Future<List<_i6.Message>>);

  @override
  _i10.Future<Map<String, dynamic>> createMatch(
    String? userId1,
    String? userId2,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMatch,
          [
            userId1,
            userId2,
          ],
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<_i6.Message> sendMessage(
    String? matchId,
    String? senderId,
    String? text,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [
            matchId,
            senderId,
            text,
          ],
        ),
        returnValue: _i10.Future<_i6.Message>.value(_FakeMessage_4(
          this,
          Invocation.method(
            #sendMessage,
            [
              matchId,
              senderId,
              text,
            ],
          ),
        )),
      ) as _i10.Future<_i6.Message>);

  @override
  _i10.Future<void> unmatch(String? matchId) => (super.noSuchMethod(
        Invocation.method(
          #unmatch,
          [matchId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i6.Message?> getLastMessage(String? matchId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastMessage,
          [matchId],
        ),
        returnValue: _i10.Future<_i6.Message?>.value(),
      ) as _i10.Future<_i6.Message?>);

  @override
  _i10.Future<Map<String, _i6.Message?>> batchGetLastMessages(
          List<String>? matchIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchGetLastMessages,
          [matchIds],
        ),
        returnValue: _i10.Future<Map<String, _i6.Message?>>.value(
            <String, _i6.Message?>{}),
      ) as _i10.Future<Map<String, _i6.Message?>>);

  @override
  _i10.Future<Map<String, int>> getUnreadCounts(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnreadCounts,
          [userId],
        ),
        returnValue: _i10.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i10.Future<Map<String, int>>);

  @override
  _i10.Future<void> markMessagesAsRead(
    String? matchId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMessagesAsRead,
          [
            matchId,
            userId,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i4.ApiResult<T>> get<T>(
    String? path, {
    T Function(Map<String, dynamic>)? parser,
    Map<String, String>? queryParameters,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #parser: parser,
            #queryParameters: queryParameters,
            #timeout: timeout,
          },
        ),
        returnValue: _i10.Future<_i4.ApiResult<T>>.value(_FakeApiResult_2<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #parser: parser,
              #queryParameters: queryParameters,
              #timeout: timeout,
            },
          ),
        )),
      ) as _i10.Future<_i4.ApiResult<T>>);

  @override
  _i10.Future<_i4.ApiResult<T>> post<T>(
    String? path, {
    Object? body,
    T Function(Map<String, dynamic>)? parser,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #body: body,
            #parser: parser,
            #timeout: timeout,
          },
        ),
        returnValue: _i10.Future<_i4.ApiResult<T>>.value(_FakeApiResult_2<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #body: body,
              #parser: parser,
              #timeout: timeout,
            },
          ),
        )),
      ) as _i10.Future<_i4.ApiResult<T>>);

  @override
  _i10.Future<_i4.ApiResult<T>> put<T>(
    String? path, {
    Object? body,
    T Function(Map<String, dynamic>)? parser,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #body: body,
            #parser: parser,
            #timeout: timeout,
          },
        ),
        returnValue: _i10.Future<_i4.ApiResult<T>>.value(_FakeApiResult_2<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #body: body,
              #parser: parser,
              #timeout: timeout,
            },
          ),
        )),
      ) as _i10.Future<_i4.ApiResult<T>>);

  @override
  _i10.Future<_i4.ApiResult<T>> delete<T>(
    String? path, {
    T Function(Map<String, dynamic>)? parser,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #parser: parser,
            #timeout: timeout,
          },
        ),
        returnValue: _i10.Future<_i4.ApiResult<T>>.value(_FakeApiResult_2<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #parser: parser,
              #timeout: timeout,
            },
          ),
        )),
      ) as _i10.Future<_i4.ApiResult<T>>);

  @override
  _i10.Future<_i5.Response> authenticatedGet(Uri? uri) => (super.noSuchMethod(
        Invocation.method(
          #authenticatedGet,
          [uri],
        ),
        returnValue: _i10.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #authenticatedGet,
            [uri],
          ),
        )),
      ) as _i10.Future<_i5.Response>);

  @override
  _i10.Future<_i5.Response> authenticatedPost(
    Uri? uri, {
    Object? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticatedPost,
          [uri],
          {#body: body},
        ),
        returnValue: _i10.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #authenticatedPost,
            [uri],
            {#body: body},
          ),
        )),
      ) as _i10.Future<_i5.Response>);

  @override
  _i10.Future<_i5.Response> authenticatedPut(
    Uri? uri, {
    Object? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticatedPut,
          [uri],
          {#body: body},
        ),
        returnValue: _i10.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #authenticatedPut,
            [uri],
            {#body: body},
          ),
        )),
      ) as _i10.Future<_i5.Response>);

  @override
  _i10.Future<_i5.Response> authenticatedDelete(Uri? uri) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticatedDelete,
          [uri],
        ),
        returnValue: _i10.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #authenticatedDelete,
            [uri],
          ),
        )),
      ) as _i10.Future<_i5.Response>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SubscriptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionService extends _i1.Mock
    implements _i14.SubscriptionService {
  MockSubscriptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasPremiumAccess => (super.noSuchMethod(
        Invocation.getter(#hasPremiumAccess),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isFreeUser => (super.noSuchMethod(
        Invocation.getter(#isFreeUser),
        returnValue: false,
      ) as bool);

  @override
  bool get isRevenueCatConfigured => (super.noSuchMethod(
        Invocation.getter(#isRevenueCatConfigured),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setAuthToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setAuthToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> initialize(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [userId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> checkSubscriptionStatus() => (super.noSuchMethod(
        Invocation.method(
          #checkSubscriptionStatus,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i15.PaywallResult> presentPaywall(
          {bool? displayCloseButton = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #presentPaywall,
          [],
          {#displayCloseButton: displayCloseButton},
        ),
        returnValue: _i10.Future<_i15.PaywallResult>.value(
            _i15.PaywallResult.notPresented),
      ) as _i10.Future<_i15.PaywallResult>);

  @override
  _i10.Future<bool> presentPaywallIfNeeded() => (super.noSuchMethod(
        Invocation.method(
          #presentPaywallIfNeeded,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> purchasePackage(_i16.Package? package) =>
      (super.noSuchMethod(
        Invocation.method(
          #purchasePackage,
          [package],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> restorePurchases() => (super.noSuchMethod(
        Invocation.method(
          #restorePurchases,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> presentCustomerCenter(_i17.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #presentCustomerCenter,
          [context],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  List<_i16.Package> getAvailablePackages() => (super.noSuchMethod(
        Invocation.method(
          #getAvailablePackages,
          [],
        ),
        returnValue: <_i16.Package>[],
      ) as List<_i16.Package>);

  @override
  _i10.Future<bool> checkTrialOrIntroEligibility(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkTrialOrIntroEligibility,
          [productId],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  bool canLike() => (super.noSuchMethod(
        Invocation.method(
          #canLike,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool canSendMessage() => (super.noSuchMethod(
        Invocation.method(
          #canSendMessage,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool canViewProfiles() => (super.noSuchMethod(
        Invocation.method(
          #canViewProfiles,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  int getLikesRemaining() => (super.noSuchMethod(
        Invocation.method(
          #getLikesRemaining,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  int getMessagesRemaining() => (super.noSuchMethod(
        Invocation.method(
          #getMessagesRemaining,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i10.Future<void> useLike() => (super.noSuchMethod(
        Invocation.method(
          #useLike,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> useMessage() => (super.noSuchMethod(
        Invocation.method(
          #useMessage,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DiscoveryPreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiscoveryPreferencesService extends _i1.Mock
    implements _i7.DiscoveryPreferencesService {
  MockDiscoveryPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.DiscoveryFilters get filters => (super.noSuchMethod(
        Invocation.getter(#filters),
        returnValue: _FakeDiscoveryFilters_5(
          this,
          Invocation.getter(#filters),
        ),
      ) as _i7.DiscoveryFilters);

  @override
  List<String> get seenProfileIds => (super.noSuchMethod(
        Invocation.getter(#seenProfileIds),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get passedProfileIds => (super.noSuchMethod(
        Invocation.getter(#passedProfileIds),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get likedProfileIds => (super.noSuchMethod(
        Invocation.getter(#likedProfileIds),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get hasSeenTutorial => (super.noSuchMethod(
        Invocation.getter(#hasSeenTutorial),
        returnValue: false,
      ) as bool);

  @override
  int get totalSeenCount => (super.noSuchMethod(
        Invocation.getter(#totalSeenCount),
        returnValue: 0,
      ) as int);

  @override
  int get passedCount => (super.noSuchMethod(
        Invocation.getter(#passedCount),
        returnValue: 0,
      ) as int);

  @override
  int get likedCount => (super.noSuchMethod(
        Invocation.getter(#likedCount),
        returnValue: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateFilters(_i7.DiscoveryFilters? filters) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFilters,
          [filters],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> clearFilters() => (super.noSuchMethod(
        Invocation.method(
          #clearFilters,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> recordProfileAction(
    String? userId,
    String? action,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordProfileAction,
          [
            userId,
            action,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> undoLastAction() => (super.noSuchMethod(
        Invocation.method(
          #undoLastAction,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> undoLastActionSilent() => (super.noSuchMethod(
        Invocation.method(
          #undoLastActionSilent,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  bool hasSeenProfile(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #hasSeenProfile,
          [userId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<void> clearSeenProfiles() => (super.noSuchMethod(
        Invocation.method(
          #clearSeenProfiles,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> saveCurrentIndex(int? index) => (super.noSuchMethod(
        Invocation.method(
          #saveCurrentIndex,
          [index],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> clearSavedIndex() => (super.noSuchMethod(
        Invocation.method(
          #clearSavedIndex,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> markTutorialAsSeen() => (super.noSuchMethod(
        Invocation.method(
          #markTutorialAsSeen,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> resetTutorial() => (super.noSuchMethod(
        Invocation.method(
          #resetTutorial,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i18.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLocationEnabled => (super.noSuchMethod(
        Invocation.getter(#isLocationEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get hasPermission => (super.noSuchMethod(
        Invocation.getter(#hasPermission),
        returnValue: false,
      ) as bool);

  @override
  bool get isUpdating => (super.noSuchMethod(
        Invocation.getter(#isUpdating),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> checkLocationService() => (super.noSuchMethod(
        Invocation.method(
          #checkLocationService,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> checkPermission() => (super.noSuchMethod(
        Invocation.method(
          #checkPermission,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> requestPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestPermission,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<_i18.GeoLocation?> getCurrentLocation() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentLocation,
          [],
        ),
        returnValue: _i10.Future<_i18.GeoLocation?>.value(),
      ) as _i10.Future<_i18.GeoLocation?>);

  @override
  _i10.Future<bool> updateLocation() => (super.noSuchMethod(
        Invocation.method(
          #updateLocation,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  void startPeriodicUpdates() => super.noSuchMethod(
        Invocation.method(
          #startPeriodicUpdates,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopPeriodicUpdates() => super.noSuchMethod(
        Invocation.method(
          #stopPeriodicUpdates,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  double? distanceTo(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #distanceTo,
        [
          latitude,
          longitude,
        ],
      )) as double?);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
