// Mocks generated by Mockito 5.4.6 from annotations
// in vlvt/test/services/location_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i9;

import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:vlvt/models/profile.dart' as _i3;
import 'package:vlvt/services/auth_service.dart' as _i2;
import 'package:vlvt/services/base_api_service.dart' as _i4;
import 'package:vlvt/services/profile_api_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthService_0 extends _i1.SmartFake implements _i2.AuthService {
  _FakeAuthService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfile_1 extends _i1.SmartFake implements _i3.Profile {
  _FakeProfile_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResult_2<T1> extends _i1.SmartFake implements _i4.ApiResult<T1> {
  _FakeApiResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_3 extends _i1.SmartFake implements _i5.Response {
  _FakeResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileApiService extends _i1.Mock implements _i6.ProfileApiService {
  MockProfileApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i2.AuthService get authService => (super.noSuchMethod(
        Invocation.getter(#authService),
        returnValue: _FakeAuthService_0(
          this,
          Invocation.getter(#authService),
        ),
      ) as _i2.AuthService);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<_i3.Profile> getProfile(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [userId],
        ),
        returnValue: _i8.Future<_i3.Profile>.value(_FakeProfile_1(
          this,
          Invocation.method(
            #getProfile,
            [userId],
          ),
        )),
      ) as _i8.Future<_i3.Profile>);

  @override
  _i8.Future<List<_i3.Profile>> getDiscoveryProfiles({
    int? minAge,
    int? maxAge,
    double? maxDistance,
    List<String>? interests,
    List<String>? excludeUserIds,
    bool? verifiedOnly,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDiscoveryProfiles,
          [],
          {
            #minAge: minAge,
            #maxAge: maxAge,
            #maxDistance: maxDistance,
            #interests: interests,
            #excludeUserIds: excludeUserIds,
            #verifiedOnly: verifiedOnly,
          },
        ),
        returnValue: _i8.Future<List<_i3.Profile>>.value(<_i3.Profile>[]),
      ) as _i8.Future<List<_i3.Profile>>);

  @override
  _i8.Future<_i3.Profile> createProfile(_i3.Profile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProfile,
          [profile],
        ),
        returnValue: _i8.Future<_i3.Profile>.value(_FakeProfile_1(
          this,
          Invocation.method(
            #createProfile,
            [profile],
          ),
        )),
      ) as _i8.Future<_i3.Profile>);

  @override
  _i8.Future<_i3.Profile> updateProfile(_i3.Profile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [profile],
        ),
        returnValue: _i8.Future<_i3.Profile>.value(_FakeProfile_1(
          this,
          Invocation.method(
            #updateProfile,
            [profile],
          ),
        )),
      ) as _i8.Future<_i3.Profile>);

  @override
  _i8.Future<Map<String, _i3.Profile>> batchGetProfiles(
          List<String>? userIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchGetProfiles,
          [userIds],
        ),
        returnValue:
            _i8.Future<Map<String, _i3.Profile>>.value(<String, _i3.Profile>{}),
      ) as _i8.Future<Map<String, _i3.Profile>>);

  @override
  _i8.Future<int> searchUserCount(Map<String, dynamic>? criteria) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchUserCount,
          [criteria],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<bool> updateLocation(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocation,
          [
            latitude,
            longitude,
          ],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<Map<String, dynamic>> uploadPhoto(String? imagePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPhoto,
          [imagePath],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<void> deletePhoto(String? photoId) => (super.noSuchMethod(
        Invocation.method(
          #deletePhoto,
          [photoId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> reorderPhotos(List<String>? photoUrls) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderPhotos,
          [photoUrls],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>> swipe({
    required String? targetUserId,
    required String? action,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #swipe,
          [],
          {
            #targetUserId: targetUserId,
            #action: action,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getReceivedLikes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getReceivedLikes,
          [],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getSentLikes() => (super.noSuchMethod(
        Invocation.method(
          #getSentLikes,
          [],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<Map<String, dynamic>> checkProfileCompletion() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkProfileCompletion,
          [],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<_i4.ApiResult<T>> get<T>(
    String? path, {
    T Function(Map<String, dynamic>)? parser,
    Map<String, String>? queryParameters,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #parser: parser,
            #queryParameters: queryParameters,
            #timeout: timeout,
          },
        ),
        returnValue: _i8.Future<_i4.ApiResult<T>>.value(_FakeApiResult_2<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #parser: parser,
              #queryParameters: queryParameters,
              #timeout: timeout,
            },
          ),
        )),
      ) as _i8.Future<_i4.ApiResult<T>>);

  @override
  _i8.Future<_i4.ApiResult<T>> post<T>(
    String? path, {
    Object? body,
    T Function(Map<String, dynamic>)? parser,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #body: body,
            #parser: parser,
            #timeout: timeout,
          },
        ),
        returnValue: _i8.Future<_i4.ApiResult<T>>.value(_FakeApiResult_2<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #body: body,
              #parser: parser,
              #timeout: timeout,
            },
          ),
        )),
      ) as _i8.Future<_i4.ApiResult<T>>);

  @override
  _i8.Future<_i4.ApiResult<T>> put<T>(
    String? path, {
    Object? body,
    T Function(Map<String, dynamic>)? parser,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #body: body,
            #parser: parser,
            #timeout: timeout,
          },
        ),
        returnValue: _i8.Future<_i4.ApiResult<T>>.value(_FakeApiResult_2<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #body: body,
              #parser: parser,
              #timeout: timeout,
            },
          ),
        )),
      ) as _i8.Future<_i4.ApiResult<T>>);

  @override
  _i8.Future<_i4.ApiResult<T>> delete<T>(
    String? path, {
    T Function(Map<String, dynamic>)? parser,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #parser: parser,
            #timeout: timeout,
          },
        ),
        returnValue: _i8.Future<_i4.ApiResult<T>>.value(_FakeApiResult_2<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #parser: parser,
              #timeout: timeout,
            },
          ),
        )),
      ) as _i8.Future<_i4.ApiResult<T>>);

  @override
  _i8.Future<_i5.Response> authenticatedGet(Uri? uri) => (super.noSuchMethod(
        Invocation.method(
          #authenticatedGet,
          [uri],
        ),
        returnValue: _i8.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #authenticatedGet,
            [uri],
          ),
        )),
      ) as _i8.Future<_i5.Response>);

  @override
  _i8.Future<_i5.Response> authenticatedPost(
    Uri? uri, {
    Object? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticatedPost,
          [uri],
          {#body: body},
        ),
        returnValue: _i8.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #authenticatedPost,
            [uri],
            {#body: body},
          ),
        )),
      ) as _i8.Future<_i5.Response>);

  @override
  _i8.Future<_i5.Response> authenticatedPut(
    Uri? uri, {
    Object? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticatedPut,
          [uri],
          {#body: body},
        ),
        returnValue: _i8.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #authenticatedPut,
            [uri],
            {#body: body},
          ),
        )),
      ) as _i8.Future<_i5.Response>);

  @override
  _i8.Future<_i5.Response> authenticatedDelete(Uri? uri) => (super.noSuchMethod(
        Invocation.method(
          #authenticatedDelete,
          [uri],
        ),
        returnValue: _i8.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #authenticatedDelete,
            [uri],
          ),
        )),
      ) as _i8.Future<_i5.Response>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
